### PR TITLE
bump to 40

### PR DESCRIPTION
**Pull request by bilelmoussaoui**

### CODE REVIEW

**Comment by evfool** [comment]
Based on the failure log it seems to me that the appdata patch is required (it complains about releases). I will start tracking the releases for swell-foop in appdata too starting from the next upstream release, until then, we need to keep the releases in this repo as a patch.

**Comment by bilelmoussaoui** [comment]
> Based on the failure log it seems to me that the appdata patch is required (it complains about releases). I will start tracking the releases for swell-foop in appdata too starting from the next upstream release, until then, we need to keep the releases in this repo as a patch.

Yes I sent a patch to add the release tag upstream

**Comment by neildarlow** [comment]
This relies on GNOME runtime 3.36 which was EOL'd in February 2021. If it can't be built against runtime 40, could 3.38 be used instead?

**Comment by hfiguiere** [comment]
The OP needs to patch the appdata. Or someone resubmit the PR with the proper changes.

**Comment by neildarlow** [comment]
Thank you for this!

**Pull request merged**
